name: lazy_loading_list_view
description: A package for creating a ListView that handles lazy loading, pagination, pull-to-refresh, and a custom empty state.
version: 0.0.5
homepage: https://github.com/Caffeinated-Code-Ltd/lazy-loading-list-view

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
