name: lazy_loading_list_view
description: A Flutter package for creating a ListView with lazy loading and pagination.
version: 0.0.2
homepage: https://github.com/Caffeinated-Code-Ltd/lazy-loading-list-view

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
